/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gracefulsoul;

import gracefulsoul.connect.JschConnector;
import gracefulsoul.vo.ActionVo;
import gracefulsoul.vo.InstanceVo;

public class JschApplication {
    
	private static JschConnector connector = new JschConnector(1);
	
	public static void main(String[] args) {
		try {
			connector.connect(initInstanceVo());
			download();
			upload();
		} finally {
			connector.disconnect();
		}
	}
	
	private static InstanceVo initInstanceVo() {
		InstanceVo instanceVo = new InstanceVo();
		instanceVo.setHost("127.0.0.1");
		instanceVo.setPort(22);
		instanceVo.setUserName("root");
		instanceVo.setPassword("root");
//		instanceVo.setPrivateKey("C:\\Users\\GracefulSoul\\.ssh\\id_rsa");
//		instanceVo.setPassphrase("Test!12");
		return instanceVo;
	}
	
	private static void download() {
		ActionVo actionVo = new ActionVo();
		actionVo.setTargetDir("/root/.ssh/");
		actionVo.setFileName("authorized_keys");
		if (connector.check(actionVo)) {
			actionVo.setDestinationDir("C:\\Users\\GracefulSoul\\.ssh\\");
			connector.download(actionVo);
		}
	}
	
	private static void upload() {
		ActionVo actionVo = new ActionVo();
		actionVo.setTargetDir("C:\\Users\\GracefulSoul\\.ssh\\");
		actionVo.setFileName("id_rsa");
		actionVo.setDestinationDir("/root/.ssh/");
		connector.download(actionVo);
	}
	
}
